FROM mcr.microsoft.com/dotnet/sdk:8.0 AS test
WORKDIR /app

COPY ./src ./src
COPY ./test ./test

WORKDIR /app
RUN dotnet restore src/ProductService.sln

RUN dotnet build src/ProductService.sln -c Debug

RUN mkdir -p /TestResults

RUN dotnet test test/ProductService.Tests/ProductService.Tests.csproj \
    --configuration Debug \
    --logger "trx;LogFileName=/TestResults/test_results.trx" \
    --logger "console;verbosity=detailed" \
    --collect "Code Coverage" \
    --results-directory "/TestResults" || true